### ISSUE TITLE
BlurView is not working in signed-release apk

### ISSUE THREAD

**Issue by madiguzel** [mmin18/RealtimeBlurView#15]
Hi,

Thanks for this useful component. It works in debug mode as expected but i cannot get the blurview work in signed release apk. Is there any configuration for release mode? Any proguard rules?

# _**SIGNED RELEASE APK**_
![release](https://user-images.githubusercontent.com/1685245/29007127-8248ded8-7b05-11e7-8783-fb60766de100.jpg)

# _**DEBUG APK**_
![debug](https://user-images.githubusercontent.com/1685245/29007128-82815970-7b05-11e7-8648-b7694ca8bd4e.jpg)

Thanks in advance...

**Comment by mmin18** [comment]
No proguard rule needed. Does it crash or it just not working. Can you
check logcat.

**Comment by madiguzel** [comment]
Hi again,

It doesn't crash but I see lots of error logs in logcat like:

20:40:57.675 11034-11034/? E/RenderScript_jni: Error loading RS jni library: java.lang.UnsatisfiedLinkError: JNI_OnLoad failed on a previous attempt to load "/data/app/com.example.myapp-1/lib/arm64/librsjni.so"
08-08 20:40:57.679 11034-11042/? E/System: Uncaught exception thrown by finalizer
08-08 20:40:57.680 11034-11042/? E/System: android.support.v8.renderscript.RSInvalidStateException: Calling RS with no Context active.
                                               at android.support.v8.renderscript.RenderScript.g(RenderScript.java:1225)
                                               at android.support.v8.renderscript.RenderScript.d(RenderScript.java:320)
                                               at android.support.v8.renderscript.RenderScript.helpDestroy(RenderScript.java:1655)
                                               at android.support.v8.renderscript.RenderScript.finalize(RenderScript.java:1689)
                                               at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                               at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                               at java.lang.Thread.run(Thread.java:761)

**Comment by madiguzel** [comment]
Hi again,

I founded the solution. It works perfectly now.

When **minifyEnabled** is **true** in gradle file, we need to add the following proguard rule:

`-keep class android.support.v8.renderscript.** { *; }`

**Comment by madiguzel** [comment]
Hi again,

I founded the solution. It works perfectly now.

When **minifyEnabled** is **true** in gradle file, we need to add the following proguard rule:

`-keep class android.support.v8.renderscript.** { *; }`

**Comment by kirilamenski** [comment]
After migration to androidx library can also help you:
```gradle
-keep class androidx.renderscript.** { *; }
```
