### ISSUE TITLE
我的buildToolsVersion 是28了

### ISSUE THREAD

**Issue by zanezha0** [mmin18/RealtimeBlurView#32]
java.lang.RuntimeException: Error loading RS jni library, Upgrade buildToolsVersion="24.0.2" or higher may solve this issue
        at com.github.mmin18.widget.RealtimeBlurView.prepare(RealtimeBlurView.java:151)
        at com.github.mmin18.widget.RealtimeBlurView$1.onPreDraw(RealtimeBlurView.java:222)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2402)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1439)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6899)

**Comment by Attect** [comment]
https://github.com/Attect/RealtimeBlurView
改一改配置就好了

**Comment by mmin18** [comment]
Resolved in v1.2
