### ISSUE TITLE
 java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by yuanjl29598** [mmin18/RealtimeBlurView#47]
api 28,how fix the bug ? 
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
        at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:550)
        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:557)
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:127)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1504)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1342)
        at android.view.View.draw(View.java:20207)
        at android.view.View.draw(View.java:20077)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20075)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20075)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20075)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at com.github.mmin18.widget.RealtimeBlurView$1.onPreDraw(RealtimeBlurView.java:265)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1049)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2475)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7185)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by hsnmrd** [comment]
same problem

**Comment by paulocoutinhox** [comment]
same problem

**Comment by paulocoutinhox** [comment]
any solution or fork?

**Comment by paulocoutinhox** [comment]
im using it with Coil library, so in coil i can disable hardware bitmap on each place that use this realtime blur view, but the best way is fix it here or if anyone knows how to do it, i can make a fork to fix.

**Comment by shaozucheng** [comment]
我也遇到同样的问题，求解
