### ISSUE TITLE
android.renderscript.RSInvalidStateException: Calling RS with no Context active

### ISSUE THREAD

**Issue by frank86225383** [mmin18/RealtimeBlurView#59]
android.renderscript.RSInvalidStateException: Calling RS with no Context active.
	at android.renderscript.RenderScript.validate(RenderScript.java:1255)
	at android.renderscript.Allocation.copyFrom(Allocation.java:992)
	at t4.a.a(AndroidStockBlurImpl.java:1)
	at com.github.mmin18.widget.RealtimeBlurView.j(RealtimeBlurView.java:1)
	at com.github.mmin18.widget.RealtimeBlurView$a.onPreDraw(RealtimeBlurView.java:26)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2854)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1817)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7779)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by kangwf** [comment]
请问有解决吗？我也碰到了一样的问题

**Comment by Danniel-yan** [comment]
> 请问有解决吗？我也碰到了一样的问题
请问 您有解决吗？

**Comment by kangwf** [comment]
您的来信已收到，祝生活愉快

**Comment by kangwf** [comment]
> 

用try catch拦截了不会崩溃，但是触发的时候模糊效果也没了

**Comment by rachanhv** [comment]
Still having the same issue, Is there any solution to this issue.

I am using 'com.github.mmin18:realtimeblurview:1.2.1', is there any latest release which addressed this issues?

Fatal Exception: android.renderscript.RSInvalidStateException: Calling RS with no Context active.
       at android.renderscript.RenderScript.validate(RenderScript.java:1246)
       at android.renderscript.Allocation.copyFrom(Allocation.java:996)
       at com.github.mmin18.widget.AndroidStockBlurImpl.blur(AndroidStockBlurImpl.java:66)
       at com.github.mmin18.widget.RealtimeBlurView.blur(RealtimeBlurView.java:233)
       at com.github.mmin18.widget.RealtimeBlurView$1.onPreDraw(RealtimeBlurView.java:273)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3362)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:780)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
